### ISSUE TITLE
Question about the feature fusion in the code

### ISSUE THREAD

**Issue by USTCLH** [WuDH2000/CrossMamba#1]
https://github.com/WuDH2000/CrossMamba/blob/b6d98f416e803038e387834c84f02d4b92bec933/selective_scan_interface_ca.py#L196

What is the difference between this and the input concatenation in the original Mamba?

**Comment by WuDH2000** [comment]
The q_dbl is generated from the query in the cross-attention mechanism, while the x_dbl is from the key and value. In the original Mamba, the query, key and value are from the same input sequence, while in CrossMamba, the query is from the other sequence.

**Comment by USTCLH** [comment]
Thank you for your reply! Is the cross-attention mechanism implemented after the code snippet I pointed out? If so, I would like to ask, if the query and key/value were concatenated at the initial input and then fed into the original Mamba, would it be similar to your implementation of CrossMamba?

**Comment by WuDH2000** [comment]
There are differences between them. You can check the original paper on arxiv. In CrossMamba, the query is used to generate C in Mamba.  If you just concatenate them, there will be no difference between those parameters in the state space models.
